version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30
    working_directory: ~/cj
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2048m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: dumb

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Check code style and android lint
          command: ./gradlew spotlessCheck lintDebug --stacktrace
      - store_artifacts:
          path: './app/build/reports'
      - persist_to_workspace:
          root: .
          paths:
            - build
            - ./**/build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build